### ISSUE TITLE
Feature Extraction Missing

### ISSUE THREAD

**Issue by Adarshs169** [sidthakur08/NFL-Prediction-model#1]
I think you should perform feature Extraction before training your model using Random Forest. Neural networks don't require feature selection but for Random Forest u have to do feature Extraction for better results.

**Comment by sidthakur08** [comment]
As mentioned in the Readme file, these features have been chosen only after applying Feature Selection methods like looking the Pearson's Correlation Coefficient for the features and applying Backwards elimination. It's just that I haven't included it in the same notebook but yes surely i'll be adding it in the future commits and learn more Feature Selection methods like Chi-Squared and Lasso Regression techniques in the hopes of attaining better features for better accuracy.
Thanks for mentioning this issue and i'll be looking to resolve this with the addition of better feature selection techniques. 
I hope this is enough to close this issue.
